### ISSUE TITLE
使用publish的时候会报 Cannot read property 'granted' of undefined

### ISSUE THREAD

**Issue by leochen-g** [lp-liupan/egg-mqtt-plugin#1]
看了源码，发现这里的`if (data.granted)`改成`if (data && data.granted)`会更好点，因为我log了一下，发现data是undefined

![image](https://user-images.githubusercontent.com/20028566/115188593-b81a8e80-a117-11eb-9f98-d3a725fc96a8.png)

**Comment by lp-liupan** [comment]
谢谢，已经修改了，确实有这个问题。
